# Generated by Django 5.2.5 on 2026-04-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_cantidad_alter_producto_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
