# Generated by Django 5.2.5 on 2026-04-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_joya'),
    ]

    operations = [
        migrations.AddField(
            model_name='joya',
            name='categoria',
            field=models.CharField(choices=[('bijou', 'Bijou'), ('enchapados', 'Enchapados'), ('gangas', 'Gangas')], default='bijou', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('bijou', 'Bijou'), ('enchapados', 'Enchapados'), ('gangas', 'Gangas')], default='enchapados', max_length=20),
        ),
    ]
