# Generated by Django 5.2.5 on 2026-04-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_joya_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='joya',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='joya',
            name='categoria',
            field=models.CharField(choices=[('bijou', 'Bijou'), ('acero_quirurgico', 'Acero quirúrgico'), ('enchapados', 'Enchapados'), ('gangas', 'Gangas')], default='bijou', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('bijou', 'Bijou'), ('acero_quirurgico', 'Acero quirúrgico'), ('enchapados', 'Enchapados'), ('gangas', 'Gangas')], default='enchapados', max_length=20),
        ),
    ]
