# Generated by Django 5.2.5 on 2026-04-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_joyaimagen_productoimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
