# Generated by Django 5.2.5 on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_producto_temporada_invierno_alter_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joya',
            name='categoria',
            field=models.CharField(choices=[('bijou', 'Bijou'), ('acero_quirurgico', 'Acero quirúrgico'), ('enchapados', 'Enchapados'), ('accesorios', 'Accesorios'), ('alpaca', 'Alpaca'), ('gangas', 'Gangas')], default='bijou', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('bijou', 'Bijou'), ('acero_quirurgico', 'Acero quirúrgico'), ('enchapados', 'Enchapados'), ('accesorios', 'Accesorios'), ('alpaca', 'Alpaca'), ('gangas', 'Gangas')], default='enchapados', max_length=20),
        ),
    ]
