# Generated by Django 5.2.5 on 2026-04-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_alter_categoria_add_accesorios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='temporada_invierno',
        ),
        migrations.AlterField(
            model_name='joya',
            name='categoria',
            field=models.CharField(choices=[('bijou', 'Bijou'), ('acero_quirurgico', 'Acero quirúrgico'), ('enchapados', 'Enchapados'), ('accesorios', 'Accesorios'), ('alpaca', 'Alpaca'), ('gangas', 'Gangas'), ('temporada_invierno', 'Temporada de invierno')], default='bijou', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('bijou', 'Bijou'), ('acero_quirurgico', 'Acero quirúrgico'), ('enchapados', 'Enchapados'), ('accesorios', 'Accesorios'), ('alpaca', 'Alpaca'), ('gangas', 'Gangas'), ('temporada_invierno', 'Temporada de invierno')], default='enchapados', max_length=20),
        ),
    ]
