# Generated by Django 5.2.5 on 2026-05-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_categoria_temporada_invierno_quitar_booleano'),
    ]

    operations = [
        migrations.AddField(
            model_name='adquirido',
            name='numero_orden',
            field=models.CharField(blank=True, db_index=True, max_length=24, null=True, unique=True),
        ),
    ]
