# Generated by Django 5.2.5 on 2026-05-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_ordencompra_ordencompraitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='estado_orden',
            field=models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('', 'Sin seleccionar'), ('transferencia', 'Transferencia bancaria'), ('efectivo', 'Efectivo al coordinar envio'), ('giros', 'Giros'), ('deposito', 'Deposito')], default='', max_length=20),
        ),
    ]
