# Generated by Django 5.2.5 on 2026-05-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0017_ordencompra_estado_orden_ordencompra_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='pago_notificado',
            field=models.BooleanField(default=False),
        ),
    ]
